version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./mdx-components.tsx:/app/mdx-components.tsx
